
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminServerService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:5001/admin?wsdl")
public class AdminServerService
    extends Service
{

    private final static URL ADMINSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINSERVERSERVICE_EXCEPTION;
    private final static QName ADMINSERVERSERVICE_QNAME = new QName("http://ws/", "AdminServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5001/admin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINSERVERSERVICE_WSDL_LOCATION = url;
        ADMINSERVERSERVICE_EXCEPTION = e;
    }

    public AdminServerService() {
        super(__getWsdlLocation(), ADMINSERVERSERVICE_QNAME);
    }

    public AdminServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINSERVERSERVICE_QNAME, features);
    }

    public AdminServerService(URL wsdlLocation) {
        super(wsdlLocation, ADMINSERVERSERVICE_QNAME);
    }

    public AdminServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINSERVERSERVICE_QNAME, features);
    }

    public AdminServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminClient
     */
    @WebEndpoint(name = "AdminServerPort")
    public AdminClient getAdminServerPort() {
        return super.getPort(new QName("http://ws/", "AdminServerPort"), AdminClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminClient
     */
    @WebEndpoint(name = "AdminServerPort")
    public AdminClient getAdminServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "AdminServerPort"), AdminClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINSERVERSERVICE_EXCEPTION!= null) {
            throw ADMINSERVERSERVICE_EXCEPTION;
        }
        return ADMINSERVERSERVICE_WSDL_LOCATION;
    }

}
