
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentServerService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:5001/student?wsdl")
public class StudentServerService
    extends Service
{

    private final static URL STUDENTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTSERVERSERVICE_EXCEPTION;
    private final static QName STUDENTSERVERSERVICE_QNAME = new QName("http://ws/", "StudentServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5001/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVERSERVICE_WSDL_LOCATION = url;
        STUDENTSERVERSERVICE_EXCEPTION = e;
    }

    public StudentServerService() {
        super(__getWsdlLocation(), STUDENTSERVERSERVICE_QNAME);
    }

    public StudentServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVERSERVICE_QNAME, features);
    }

    public StudentServerService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVERSERVICE_QNAME);
    }

    public StudentServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVERSERVICE_QNAME, features);
    }

    public StudentServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentClient
     */
    @WebEndpoint(name = "StudentServerPort")
    public StudentClient getStudentServerPort() {
        return super.getPort(new QName("http://ws/", "StudentServerPort"), StudentClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentClient
     */
    @WebEndpoint(name = "StudentServerPort")
    public StudentClient getStudentServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "StudentServerPort"), StudentClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVERSERVICE_EXCEPTION!= null) {
            throw STUDENTSERVERSERVICE_EXCEPTION;
        }
        return STUDENTSERVERSERVICE_WSDL_LOCATION;
    }

}
